### ISSUE TITLE
Wrong parameter M

### ISSUE THREAD

**Issue by julianspeith** [SRI-CSL/Bliss#1]
I have stumbled upon what I guess is a wrong choice of parameter M while writing my thesis about a related topic.

You perform rejection sampling based on the Bernoulli sampler with the relevent line being
`if (! sampler_ber_exp(&sampler, p.M - norm_v)) {`.

While you chose p.M to be P_{max} as in the BLZZRD implementation, this does not work for this rejection sampler. For the Bernoulli sampler p.M needs to be chosen as 2*sigma^2*ln(M) with the respective values for M given in the BLISS-B paper and the values for sigma given in the BLISS paper.

This is the reason why you needed to add additional bound checks at the end of the signing algorithm. When adapting your p.M, you should be able to ditch those bound checks.

**Comment by BrunoDutertre** [comment]
Thanks a lot for pointing this out.

**Comment by tlepoint** [comment]
I am a bit confused, it seems to me that `p.M=2sigma^2ln(M)` is exactly what we have (and I say it's `=Pmax`). I remember checking the value of M when we were working on the implementation, and I wrote [here](https://github.com/SRI-CSL/Bliss/blob/master/include/bliss_b_params.h#L66) why we took `p.M=P_max`. Let me explain again.

### Binary sampler call

Since we are [using the binary sampler](https://github.com/SRI-CSL/Bliss/blob/master/src/sampler.c#L48) `B = B_{exp(-x/(2sigma^2))}` that we call on `x=p.M-||v||^2`, then we need to target 

``` (*). exp(-x/(2sigma^2)) = exp(-(p.M-||v||^2)/(2sigma^2)) <= 1```

And since `||v||^2<= Pmax`, we take `p.M=Pmax`.

### Relation with `M`

Line 7 of the signing algorithm in BLISS-B shows that it's enough to choose `M` such that 

``` (**).  1/(M*exp(-||v||^2/(2sigma^2)) <= 1 ```

### Choice of `M` so that Eqs. (*) and (**) are the same

We obtain exactly the formula that you state, i.e.,  `M=exp(p.M/(2sigma^2))`. (In particular, we never said that p.M was the ln of M.)


#

Am I missing something?

**Comment by julianspeith** [comment]
> Am I missing something?

No, you're not. I did my math again and it looks like I made a mistake the first time. Turns out that your values were right all along. Sorry for wasting your time...

**Comment by tlepoint** [comment]
No worries, it’s always good to double check the math! :-)
